version: '3.4'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:dev -- -L
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  db:
    restart: always
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: barbellhero
    volumes:
      - /usr/postgres/data

    