version: '3.4'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:dev -- -L
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules